"""add stats infra: room status/ended_at and room_participants

Revision ID: 1fb1b0376169
Revises: 257334174557
Create Date: 2026-09-08 10:28:06.610771

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1fb1b0376169"
down_revision: str | Sequence[str] | None = "257334174557"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "room_participants",
        sa.Column("room_id", sa.UUID(), nullable=False),
        sa.Column("player_id", sa.UUID(), nullable=False),
        sa.Column("joined_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["room_id"], ["rooms.room_id"]),
        sa.PrimaryKeyConstraint("room_id", "player_id"),
    )
    op.create_index(
        "ix_room_participants_player_id", "room_participants", ["player_id"], unique=False
    )
    op.add_column(
        "rooms", sa.Column("status", sa.String(length=16), server_default="lobby", nullable=False)
    )
    op.add_column("rooms", sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True))
    op.create_index("ix_rooms_host_id", "rooms", ["host_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_rooms_host_id", table_name="rooms")
    op.drop_column("rooms", "ended_at")
    op.drop_column("rooms", "status")
    op.drop_index("ix_room_participants_player_id", table_name="room_participants")
    op.drop_table("room_participants")
    # ### end Alembic commands ###
