"""add settlements table

Revision ID: 22b8206bab6a
Revises: 1fb1b0376169
Create Date: 2026-09-08 14:13:57.421826

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "22b8206bab6a"
down_revision: str | Sequence[str] | None = "1fb1b0376169"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "settlements",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("room_id", sa.UUID(), nullable=False),
        sa.Column("game_type", sa.String(length=16), nullable=False),
        sa.Column("from_player", sa.UUID(), nullable=False),
        sa.Column("to_player", sa.UUID(), nullable=False),
        sa.Column("amount_cents", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=16), server_default="pending", nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["room_id"], ["rooms.room_id"]),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "room_id", "from_player", "to_player", name="uq_settlements_room_from_to"
        ),
    )
    op.create_index("ix_settlements_from_player", "settlements", ["from_player"], unique=False)
    op.create_index("ix_settlements_to_player", "settlements", ["to_player"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_settlements_to_player", table_name="settlements")
    op.drop_index("ix_settlements_from_player", table_name="settlements")
    op.drop_table("settlements")
    # ### end Alembic commands ###
